force-app/main/default/objects/ConnectionMessage__e/ConnectionMessage__e.object-meta.xml
<CustomObject>
    <label>Connection Message</label>
    <pluralLabel>Connection Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConnectionMessage__e/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>This will store the JSON message object</description>
    <label>Object</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectionMessage__e/fields/SenderId__c.field-meta.xml
<CustomField>
    <fullName>SenderId__c</fullName>
    <label>Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/communicationController.cls
public with sharing class communicationController {
    
    @AuraEnabled
    public static string sendMessage(String senderId, String type, String objectString) {
        ConnectionMessage__e msg=new ConnectionMessage__e(Object__c=objectString,
                                                          SenderId__c=senderId,
                                                          Type__c=type
                                                        );
        Database.SaveResult sr = EventBus.publish(msg);
        if (sr.isSuccess()) {
            return('SUCCESS');
        }
        return('FAILURE');
    }
}